---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: bosh
  name: bosh
spec:
  replicas: 1
  serviceName: bosh-set
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: bosh
      name: bosh
    spec:
      containers:
      - env:
        - name: CLUSTER_CERTIFICATE_AUTHORITY_DATA
          value: {{ required "CLUSTER_CERTIFICATE_AUTHORITY_DATA configuration missing" .Values.env.CLUSTER_CERTIFICATE_AUTHORITY_DATA | quote }}
        - name: CLUSTER_NAME
          value: {{ required "CLUSTER_NAME configuration missing" .Values.env.CLUSTER_NAME | quote }}
        - name: CLUSTER_REFRESH_TOKEN
          value: {{ required "CLUSTER_REFRESH_TOKEN configuration missing" .Values.env.CLUSTER_REFRESH_TOKEN | quote }}
        - name: CLUSTER_SERVER
          value: {{ required "CLUSTER_SERVER configuration missing" .Values.env.CLUSTER_SERVER | quote }}
        - name: CLUSTER_TOKEN
          value: {{ required "CLUSTER_TOKEN configuration missing" .Values.env.CLUSTER_TOKEN | quote }}
        - name: DIRECTOR_CERT
          valueFrom:
            secretKeyRef:
              key: director-cert
              name: secret-1
        - name: DIRECTOR_KEY
          valueFrom:
            secretKeyRef:
              key: director-key
              name: secret-1
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bosh-bosh:731b74e4ec8af113c0e4c98906170a8e0b8e5787
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: bosh
        ports:
        - containerPort: 25555
          name: director
          protocol: TCP
        - containerPort: 25556
          name: directorbackend
          protocol: TCP
        - containerPort: 25250
          name: blobstore
          protocol: TCP
        - containerPort: 4222
          name: nats
          protocol: TCP
        - containerPort: 8081
          name: powerdns
          protocol: TCP
        - containerPort: 5432
          name: postgres
          protocol: TCP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        readinessProbe:
          tcpSocket:
            port: 25555
        resources: {}
        volumeMounts:
        - mountPath: /var/vcap/store
          name: bosh-disk
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: ibmc-file-gold
        volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-file
      creationTimestamp: null
      name: bosh-disk
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20G
    status: {}
status:
  replicas: 0
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: bosh-set
  spec:
    clusterIP: None
    ports:
    - name: director
      port: 25555
      protocol: TCP
      targetPort: 0
    - name: directorbackend
      port: 25556
      protocol: TCP
      targetPort: 0
    - name: blobstore
      port: 25250
      protocol: TCP
      targetPort: 0
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: 0
    - name: powerdns
      port: 8081
      protocol: TCP
      targetPort: 0
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 0
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 0
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 0
    selector:
      skiff-role-name: bosh
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: bosh
  spec:
    ports:
    - name: director
      port: 25555
      protocol: TCP
      targetPort: director
    - name: directorbackend
      port: 25556
      protocol: TCP
      targetPort: directorbackend
    - name: blobstore
      port: 25250
      protocol: TCP
      targetPort: blobstore
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: nats
    - name: powerdns
      port: 8081
      protocol: TCP
      targetPort: powerdns
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    selector:
      skiff-role-name: bosh
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: bosh-public
  spec:
    externalIPs:
    - {{ .Values.kube.external_ip | quote }}
    ports:
    - name: director
      port: 25555
      protocol: TCP
      targetPort: director
    - name: directorbackend
      port: 25556
      protocol: TCP
      targetPort: directorbackend
    - name: blobstore
      port: 25250
      protocol: TCP
      targetPort: blobstore
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: nats
    - name: powerdns
      port: 8081
      protocol: TCP
      targetPort: powerdns
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    selector:
      skiff-role-name: bosh
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
