---
apiVersion: v1
data:
  blob-agent-password: {{ default "" .Values.blob.agent.password | b64enc | quote }}
  blob-director-password: {{ default "" .Values.blob.director.password | b64enc | quote }}
  director-cert: {{ default "" .Values.director.cert | b64enc | quote }}
  director-key: {{ default "" .Values.director.key | b64enc | quote }}
  monit-password: {{ default "" .Values.monit.password | b64enc | quote }}
  nats-http-password: {{ default "" .Values.nats.http.password | b64enc | quote }}
  nats-password: {{ default "" .Values.nats.password | b64enc | quote }}
  postgres-password: {{ default "" .Values.postgres.password | b64enc | quote }}
  webserver-password: {{ default "" .Values.webserver.password | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}