---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: postgres
  name: postgres
spec:
  replicas: 1
  serviceName: postgres-set
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: postgres
      name: postgres
    spec:
      containers:
      - env:
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bcf-postgres:4bab99b833b29d4a4df10ccbb2ec25cb30ef9d4c
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: postgres
        ports:
        - containerPort: 5524
          name: postgres
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5524
        resources: {}
        volumeMounts:
        - mountPath: /var/vcap/store
          name: postgres-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: ibmc-file-gold
        volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-file
      creationTimestamp: null
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500G
    status: {}
status:
  replicas: 0
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: postgres-set
  spec:
    clusterIP: None
    ports:
    - name: postgres
      port: 5524
      protocol: TCP
      targetPort: 0
    selector:
      skiff-role-name: postgres
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: postgres
  spec:
    ports:
    - name: postgres
      port: 5524
      protocol: TCP
      targetPort: postgres
    selector:
      skiff-role-name: postgres
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
