---
apiVersion: v1
data:
  monit-password: {{ default "passw0rd" | b64enc | quote }}
  saml-serviceprovider-cert: {{ required "SAML_SERVICEPROVIDER_CERT configuration missing" .Values.env.SAML_SERVICEPROVIDER_CERT | b64enc | quote }}
  saml-serviceprovider-key: {{ required "SAML_SERVICEPROVIDER_KEY configuration missing" .Values.env.SAML_SERVICEPROVIDER_KEY | b64enc | quote }}
  uaa-admin-client-secret: {{ required "UAA_ADMIN_CLIENT_SECRET configuration missing" .Values.env.UAA_ADMIN_CLIENT_SECRET | b64enc | quote }}
  uaa-server-cert: {{ required "UAA_SERVER_CERT configuration missing" .Values.env.UAA_SERVER_CERT | b64enc | quote }}
  uaa-server-key: {{ required "UAA_SERVER_KEY configuration missing" .Values.env.UAA_SERVER_KEY | b64enc | quote }}
  uaadb-password: {{ default "passw0rd" | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-1
