---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: director
  name: director
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: director
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: director
      name: director
    spec:
      volumes:
      - name: disk-eb97d5f7-85d5-4537-651f-ec74b8cf383d
        persistentVolumeClaim:
          claimName: disk-eb97d5f7-85d5-4537-651f-ec74b8cf383d
      containers:
      - env:
        - name: BLOB_AGENT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: blob-agent-password
              name: secret-1
        - name: BLOB_DIRECTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: blob-director-password
              name: secret-1
        - name: DIRECTOR_CERT
          valueFrom:
            secretKeyRef:
              key: director-cert
              name: secret-1
        - name: DIRECTOR_KEY
          valueFrom:
            secretKeyRef:
              key: director-key
              name: secret-1
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: nats-password
              name: secret-1
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: secret-1
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: registry-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bosh-director:latest
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: director
        ports:
        - containerPort: 25555
          name: director
          protocol: TCP
        - containerPort: 25556
          name: directorbackend
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 25555
        resources: {}
        volumeMounts:
        - mountPath: /var/vcap/store
          name: disk-eb97d5f7-85d5-4537-651f-ec74b8cf383d
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: director
spec:
  ports:
  - name: director
    port: 25555
    protocol: TCP
    targetPort: director
  - name: directorbackend
    port: 25556
    protocol: TCP
    targetPort: directorbackend
  selector:
    skiff-role-name: director
  type: NodePort

