---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: nats
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: nats
      name: nats
    spec:
      containers:
      - env:
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: NATS_HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: nats-http-password
              name: secret-1
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: nats-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bosh-nats:latest
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: nats
        ports:
        - containerPort: 4222
          name: nats
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 4222
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nats
spec:
  ports:
  - name: nats
    port: 4222
    protocol: TCP
    targetPort: nats
  selector:
    skiff-role-name: nats
  type: ClusterIP
status:
  loadBalancer: {}
