---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: postgres
      name: postgres
    spec:
      containers:
      - env:
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bosh-postgres:latest
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5432
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  selector:
    skiff-role-name: postgres
  type: ClusterIP
status:
  loadBalancer: {}
