apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-file-gold
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-file
  labels:
    skiff-volume-id: eb97d5f7-85d5-4537-651f-ec74b8cf383d
  name: disk-eb97d5f7-85d5-4537-651f-ec74b8cf383d
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
status: {}
