---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: registry
      name: registry
    spec:
      containers:
      - env:
        - name: MONIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monit-password
              name: secret-1
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: secret-1
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: registry-password
              name: secret-1
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: bluebosh/bosh-registry:1
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: registry
        ports:
        - containerPort: 25777
          name: registry
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 25777
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: registry
spec:
  ports:
  - name: registry
    port: 25777
    protocol: TCP
    targetPort: registry
  selector:
    skiff-role-name: registry
  type: ClusterIP
status:
  loadBalancer: {}
