#!/usr/bin/env bash
set -ex

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

NAMESPACE=$2
if [[ $NAMESPACE = "" ]]; then
    echo "[WARNING] You didn't specify your namespace as the second argument, use bosh as default."
    NAMESPACE=bosh
fi

has_namespace() {
    kubectl get namespace --output=name "${NAMESPACE}" >/dev/null 2>/dev/null
}

if has_namespace ; then
    kubectl delete namespace "${NAMESPACE}"
fi

printf "Waiting for namespace %s to be deleted...\n" "${NAMESPACE}"
while has_namespace ; do
    sleep 1
done

kubectl create namespace "${NAMESPACE}"

#kubectl get storageclass persistent 2>/dev/null || {
#    perl -p -e 's@storage.k8s.io/v1beta1@storage.k8s.io/v1@g' \
#        "${GIT_ROOT}/kube-test/storage-class-host-path.yml" | \
#    kubectl create -f -
#}

source env/defaults.env

CLUSTER_NAME=$1
if [[ $CLUSTER_NAME = "" ]]; then
    echo "[ERROR] You must specify your cluster name as the first argument."
    exit 1
fi
kube_config=`kubectl config view | grep "user: http"`
USER=`echo ${kube_config#*#}`
CLUSTER_SERVER=$(kubectl config view -o json | jq -r '.clusters[] | select(.name=="'$CLUSTER_NAME'") | .cluster.server')
cluster_ca_file=$(kubectl config view -o json | jq -r '.clusters[] | select(.name=="'$CLUSTER_NAME'") | .cluster."certificate-authority"')
cluster_path=$HOME/.bluemix/plugins/container-service/clusters/${CLUSTER_NAME}
#CLUSTER_CERTIFICATE_AUTHORITY_DATA=$(sed ':a;N;$ s/\n/\\n/g;ba' $cluster_path/$cluster_ca_file)
CLUSTER_CERTIFICATE_AUTHORITY_DATA=$(cat $cluster_path/$cluster_ca_file)
CLUSTER_TOKEN=$(kubectl config view -o json | jq -r '.users[] | select(.name=="https://iam.ng.bluemix.net/kubernetes#'$USER'") | .user."auth-provider"."config"."id-token"')
CLUSTER_REFRESH_TOKEN=$(kubectl config view -o json | jq -r '.users[] | select(.name=="https://iam.ng.bluemix.net/kubernetes#'$USER'") | .user."auth-provider"."config"."refresh-token"')

helm install helm \
     --namespace "${NAMESPACE}" \
     --set "env.CLUSTER_NAME=${CLUSTER_NAME}" \
     --set "env.CLUSTER_CERTIFICATE_AUTHORITY_DATA=${CLUSTER_CERTIFICATE_AUTHORITY_DATA}" \
     --set "env.CLUSTER_SERVER=${CLUSTER_SERVER}" \
     --set "env.CLUSTER_REFRESH_TOKEN=${CLUSTER_REFRESH_TOKEN}" \
     --set "env.CLUSTER_TOKEN=${CLUSTER_TOKEN}"

