env:
  CLUSTER_CERTIFICATE_AUTHORITY_DATA: null
  CLUSTER_NAME: null
  CLUSTER_REFRESH_TOKEN: null
  CLUSTER_SERVER: null
  CLUSTER_TOKEN: null
  DIRECTOR_CERT: |
    -----BEGIN CERTIFICATE-----
    MIIJDjCCBvagAwIBAgIQY3CAih7ogOg37FUhTJ421jANBgkqhkiG9w0BAQsFADAV
    MRMwEQYDVQQDEwppbnRlcm5hbENBMB4XDTE3MDkwMjEyMDA1MloXDTE5MDkwMjEy
    MDA1MlowEzERMA8GA1UEAxMIZGlyZWN0b3IwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDVuUV66exiVzdZ4CH4oLtIIHioJ8zzcJTg8H2bwFQnQxUg17gp
    gxcqYqtx/eXyawPzJXbNBW3Rxmcp99KtQmDuWjklUCcoEGrvRCzeIcm/xjjF31RG
    oL+/roWOpqB8nmY0GmuRHj/mb/xL9XJ4zWT4KbQOWII3vnrn/b3POUlRlHaTcKnO
    wzl24Oud+jJ37mqTQke9cXFWdyyARL5WXtnx1qLpT04kfsTsLrzkT8URyAdVSuY6
    Xeo3xDTzAnpjiPwy9JEWJhxtuB1YbS0bw+W3DRaN+HkJBwEsqRxVvERPFP1QOv3r
    dvDB7wd5nIb7fiOxTolQ5JSPvKWtMFGLD7jZAgMBAAGjggVaMIIFVjAOBgNVHQ8B
    Af8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQW
    BBT5T5XOtoeqp/LfCfjR+Sdrjpo+nTAfBgNVHSMEGDAWgBRDLhkMSaNwBmDPmIVh
    fBbAtzGEPjCCBOMGA1UdEQSCBNowggTWgghkaXJlY3RvcoIKKi5kaXJlY3RvcoIX
    ZGlyZWN0b3ItMC5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTEuZGlyZWN0b3ItcG9k
    ghdkaXJlY3Rvci0yLmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItMy5kaXJlY3Rvci1w
    b2SCF2RpcmVjdG9yLTQuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci01LmRpcmVjdG9y
    LXBvZIIXZGlyZWN0b3ItNi5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTcuZGlyZWN0
    b3ItcG9kghdkaXJlY3Rvci04LmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItOS5kaXJl
    Y3Rvci1wb2SCFWRpcmVjdG9yLmRpcmVjdG9yLnN2Y4IXKi5kaXJlY3Rvci5kaXJl
    Y3Rvci5zdmOCH2RpcmVjdG9yLTAuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVj
    dG9yLTEuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTIuZGlyZWN0b3It
    cG9kLnVhYS5zdmOCH2RpcmVjdG9yLTMuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2Rp
    cmVjdG9yLTQuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTUuZGlyZWN0
    b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTYuZGlyZWN0b3ItcG9kLnVhYS5zdmOC
    H2RpcmVjdG9yLTcuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTguZGly
    ZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTkuZGlyZWN0b3ItcG9kLnVhYS5z
    dmOCI2RpcmVjdG9yLmRpcmVjdG9yLnN2Yy5jbHVzdGVyLmxvY2FsgiUqLmRpcmVj
    dG9yLmRpcmVjdG9yLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0wLmRpcmVj
    dG9yLXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTEuZGlyZWN0
    b3ItcG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMi5kaXJlY3Rv
    ci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0zLmRpcmVjdG9y
    LXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTQuZGlyZWN0b3It
    cG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItNS5kaXJlY3Rvci1w
    b2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci02LmRpcmVjdG9yLXBv
    ZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTcuZGlyZWN0b3ItcG9k
    LnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItOC5kaXJlY3Rvci1wb2Qu
    dWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci05LmRpcmVjdG9yLXBvZC51
    YWEuc3ZjLmNsdXN0ZXIubG9jYWyCEmRpcmVjdG9yLmNmLWRldi5pb4IUKi5kaXJl
    Y3Rvci5jZi1kZXYuaW8wDQYJKoZIhvcNAQELBQADggIBAGw+oXVlsmGP5+1kazyE
    UCnowQLgyWghg/0U81SZl9KXlaw/xh0zJO+yDSdnKio4aHnySfgyVOgxMHdxuJDM
    tf6zO/1wga9JSr1sTKrC9JGSARJ8x2GZmSw/DxPH0stpl84hQXqOmbd3u1zMdx3P
    b/vZA4eLWAfsIoFTOtYfNnkdNLrUL8EVc9HGYodoGT1xUuq8/MGlslsTZVHf7UI3
    SUxweycyJZlpWAg0bykkhFnIOXywMZHaSFQu1PtkCDTNjfA2lUiGd37rNbuvg84D
    iDPjFwvZuWZVtBL81+D6pS88j+0sBDPHo2Wad+oS08HyZZCi8s/yRaq5/z9lXxuF
    fg4M4m1bZZoIZG78KBHw1uOWyTcOwB/X/1mx79Bu4B1LSMLRqmGiXYG40HyueVlD
    1L2BGSTtgYz9B9KiGuHaLag2l0J1ekGuVK4Je9MyPedGfhJxcJQGZAkQfh5z/jDa
    bdGcHtumCMdh5/O0V0LdyvEGRSVafKxbsTTQnikBYU2Ura/afGrN6rkZ/a5q6bDr
    r1UdqNpGFvSqE+AvABti9IB/5Nj3aNzcEyIuELS0I3pX2Tn3OgtODeL8rokhMwIl
    LDYQwu05K/PqA/KayTx4Y6e0tDyYy2oV1kFy/OJBlDVU4doRDfVQy9AirqS65KpL
    OfMLSknp9j3AjwDkTh4z8nRm
    -----END CERTIFICATE-----
  DIRECTOR_KEY: |
    -----BEGIN CERTIFICATE-----
    MIIJDjCCBvagAwIBAgIQY3CAih7ogOg37FUhTJ421jANBgkqhkiG9w0BAQsFADAV
    MRMwEQYDVQQDEwppbnRlcm5hbENBMB4XDTE3MDkwMjEyMDA1MloXDTE5MDkwMjEy
    MDA1MlowEzERMA8GA1UEAxMIZGlyZWN0b3IwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDVuUV66exiVzdZ4CH4oLtIIHioJ8zzcJTg8H2bwFQnQxUg17gp
    gxcqYqtx/eXyawPzJXbNBW3Rxmcp99KtQmDuWjklUCcoEGrvRCzeIcm/xjjF31RG
    oL+/roWOpqB8nmY0GmuRHj/mb/xL9XJ4zWT4KbQOWII3vnrn/b3POUlRlHaTcKnO
    wzl24Oud+jJ37mqTQke9cXFWdyyARL5WXtnx1qLpT04kfsTsLrzkT8URyAdVSuY6
    Xeo3xDTzAnpjiPwy9JEWJhxtuB1YbS0bw+W3DRaN+HkJBwEsqRxVvERPFP1QOv3r
    dvDB7wd5nIb7fiOxTolQ5JSPvKWtMFGLD7jZAgMBAAGjggVaMIIFVjAOBgNVHQ8B
    Af8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQW
    BBT5T5XOtoeqp/LfCfjR+Sdrjpo+nTAfBgNVHSMEGDAWgBRDLhkMSaNwBmDPmIVh
    fBbAtzGEPjCCBOMGA1UdEQSCBNowggTWgghkaXJlY3RvcoIKKi5kaXJlY3RvcoIX
    ZGlyZWN0b3ItMC5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTEuZGlyZWN0b3ItcG9k
    ghdkaXJlY3Rvci0yLmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItMy5kaXJlY3Rvci1w
    b2SCF2RpcmVjdG9yLTQuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci01LmRpcmVjdG9y
    LXBvZIIXZGlyZWN0b3ItNi5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTcuZGlyZWN0
    b3ItcG9kghdkaXJlY3Rvci04LmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItOS5kaXJl
    Y3Rvci1wb2SCFWRpcmVjdG9yLmRpcmVjdG9yLnN2Y4IXKi5kaXJlY3Rvci5kaXJl
    Y3Rvci5zdmOCH2RpcmVjdG9yLTAuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVj
    dG9yLTEuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTIuZGlyZWN0b3It
    cG9kLnVhYS5zdmOCH2RpcmVjdG9yLTMuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2Rp
    cmVjdG9yLTQuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTUuZGlyZWN0
    b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTYuZGlyZWN0b3ItcG9kLnVhYS5zdmOC
    H2RpcmVjdG9yLTcuZGlyZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTguZGly
    ZWN0b3ItcG9kLnVhYS5zdmOCH2RpcmVjdG9yLTkuZGlyZWN0b3ItcG9kLnVhYS5z
    dmOCI2RpcmVjdG9yLmRpcmVjdG9yLnN2Yy5jbHVzdGVyLmxvY2FsgiUqLmRpcmVj
    dG9yLmRpcmVjdG9yLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0wLmRpcmVj
    dG9yLXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTEuZGlyZWN0
    b3ItcG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMi5kaXJlY3Rv
    ci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0zLmRpcmVjdG9y
    LXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTQuZGlyZWN0b3It
    cG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItNS5kaXJlY3Rvci1w
    b2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci02LmRpcmVjdG9yLXBv
    ZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTcuZGlyZWN0b3ItcG9k
    LnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItOC5kaXJlY3Rvci1wb2Qu
    dWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci05LmRpcmVjdG9yLXBvZC51
    YWEuc3ZjLmNsdXN0ZXIubG9jYWyCEmRpcmVjdG9yLmNmLWRldi5pb4IUKi5kaXJl
    Y3Rvci5jZi1kZXYuaW8wDQYJKoZIhvcNAQELBQADggIBAGw+oXVlsmGP5+1kazyE
    UCnowQLgyWghg/0U81SZl9KXlaw/xh0zJO+yDSdnKio4aHnySfgyVOgxMHdxuJDM
    tf6zO/1wga9JSr1sTKrC9JGSARJ8x2GZmSw/DxPH0stpl84hQXqOmbd3u1zMdx3P
    b/vZA4eLWAfsIoFTOtYfNnkdNLrUL8EVc9HGYodoGT1xUuq8/MGlslsTZVHf7UI3
    SUxweycyJZlpWAg0bykkhFnIOXywMZHaSFQu1PtkCDTNjfA2lUiGd37rNbuvg84D
    iDPjFwvZuWZVtBL81+D6pS88j+0sBDPHo2Wad+oS08HyZZCi8s/yRaq5/z9lXxuF
    fg4M4m1bZZoIZG78KBHw1uOWyTcOwB/X/1mx79Bu4B1LSMLRqmGiXYG40HyueVlD
    1L2BGSTtgYz9B9KiGuHaLag2l0J1ekGuVK4Je9MyPedGfhJxcJQGZAkQfh5z/jDa
    bdGcHtumCMdh5/O0V0LdyvEGRSVafKxbsTTQnikBYU2Ura/afGrN6rkZ/a5q6bDr
    r1UdqNpGFvSqE+AvABti9IB/5Nj3aNzcEyIuELS0I3pX2Tn3OgtODeL8rokhMwIl
    LDYQwu05K/PqA/KayTx4Y6e0tDyYy2oV1kFy/OJBlDVU4doRDfVQy9AirqS65KpL
    OfMLSknp9j3AjwDkTh4z8nRm
    -----END CERTIFICATE-----
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA1blFeunsYlc3WeAh+KC7SCB4qCfM83CU4PB9m8BUJ0MVINe4
    KYMXKmKrcf3l8msD8yV2zQVt0cZnKffSrUJg7lo5JVAnKBBq70Qs3iHJv8Y4xd9U
    RqC/v66FjqagfJ5mNBprkR4/5m/8S/VyeM1k+Cm0DliCN7565/29zzlJUZR2k3Cp
    zsM5duDrnfoyd+5qk0JHvXFxVncsgES+Vl7Z8dai6U9OJH7E7C685E/FEcgHVUrm
    Ol3qN8Q08wJ6Y4j8MvSRFiYcbbgdWG0tG8Pltw0Wjfh5CQcBLKkcVbxETxT9UDr9
    63bwwe8HeZyG+34jsU6JUOSUj7ylrTBRiw+42QIDAQABAoIBAQCTU9EChuiNbePZ
    D7k7Q8l2UfP6rt0IX24xlXZw/GbGXebdqfbontZEQJpAzS5LKtwhK402jWyDtAn/
    kzdmeiCJjiZgg11Kr+6XG172jUIe8czHEkltGniz8OFeUZzF6wc3GZNXCQwxlLbN
    wdf0UFou+8iELx0swiDFdVP32lyhX7xsqP09P7lXmBB/kKKMD7938Ots20EUXjSu
    p0DIRmbV0L1unUjglax/y71W6tLUSleKAp3XvhvLEryeMn7Yxdb+uNZzqp1pmvnn
    rvIq0AS94oW+X9vfvVTu28TpLpucisISyGQJMzGAWUjKiMYkRyLcKLiZQ5EzJErX
    xSASIlcBAoGBAN503gCHyiSHLfEvUwxbXNagfwybGHj2VZUaOIwGVwcaN15IPK1p
    ukqVuOLuckrOXDGt31HISA4iW0EcLalgpnXz+Dg+vXCrFNGTbezFlUBZfCsC22Cv
    jWqK20NSdLGpco0eTVxzI2OXy2mt41jOq8q5KmMe+Zj/OYaKVpoKsri5AoGBAPXz
    TlnXa6VQVzftpAO9XjxLHTKRSkEhkgFQWE1bNyObartMEGR12OCODGDSX9J5hPBH
    gxvBoLMf2bsd7ICpu+hnxl2zVb0GcqgaYGfxH32GMD6MYSqkwSu2q5JeGdVNaLzJ
    kz5rkFsRnBCaJhPHnsrCNXkutDlDm6Qemzn3vrEhAoGBAKg/nbSq/xEXiIDU+Svs
    YdAWfWDsYNsD/ICT31bQaLv/cQcG/ZVu1K4ahUZlb93yK7qLNc8l+pFuHLSm+kYT
    ynKFviPUF/WB/3Hu3oHoglS0GXxyYbfDruJ4+RL25zmD3harZ3lXv9lQclGQadW+
    IiJmX4+uWrsDtd9y+8Lv+nJJAoGBANpg1Dq1KWE5OpfwKucfJyMF1sDlfDbkZc1A
    14an7QdyoYv3974bXRvVRGxbnrU1LLJj7KeifttM9nhME4gSLUQnkFv2NbSGmxtj
    gCIKWFmN4hxHbKb+bn4vzZtCblGUT+EAYfrUavJRam7bT9/UKMwDMJOOwnrt6q4I
    du87aFfBAoGBAN0Jha3QhEV1MyYTN82hQKDowgiYsZho5pFp/ynGync2k/IBDFW9
    /JKAzc8hkXPKITFEvpsb4hyxvIaDBrCz1K1E6S00HC26/cKSfx1Y0C9Hg5Y9z4tQ
    CYLtflzjlvq8Qj3tQsA/9AqclNIsG8dsnkBIenWCfndPPOiHkMJgvI5H
    -----END RSA PRIVATE KEY-----
  DNS_RECORD_NAME: null
  IP_ADDRESS: null
  KUBERNETES_NAMESPACE: null
kube:
  external_ip: 169.47.254.190
  storage_class:
    persistent: persistent
    shared: shared
