env:
  DIRECTOR_CERT: |
    -----BEGIN CERTIFICATE-----
    MIIJDzCCBvegAwIBAgIRAOZ3weoi+qSu319JGOEZAeEwDQYJKoZIhvcNAQELBQAw
    FTETMBEGA1UEAxMKaW50ZXJuYWxDQTAeFw0xNzA5MDEwMzA3NTFaFw0xOTA5MDEw
    MzA3NTFaMBMxETAPBgNVBAMTCGRpcmVjdG9yMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAvdpk6U7DxYv8PaFhH9KXFZ62Xrl3lAgAajyVQvcsG24x60Jt
    Ge/krPQIi1bO9K7Q2jl77txC7W1/b8gBSsRwiZk0qhxEY59+DE6nIyTebcm/Aci2
    ePjZB1QDkKKQAjNQVGXAjrBtKgMibOYedwdUGLPRfTx4OqC4Glx/7IUsuhuzjtzl
    ZwLjmkdMUr5K8GZCOkcIx3frGSO8t63H/lx38Ai0DU8LIZ3PsaTB4MfubnNVVAUw
    XeOsPERKzf7M3iGPZM6nb72ptNv4fQUB+rEaUukZRl2AhR/8U1z5rllB31LjiL5y
    ldy03B+1Yv0u6iGyPnpV0xrl1XnM1SCRNmPcIwIDAQABo4IFWjCCBVYwDgYDVR0P
    AQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4E
    FgQUf0bdCrkITJ0qiKd9OGESjTkk5mswHwYDVR0jBBgwFoAUZCn+ZXgUwsVy7ZSj
    Ftln+GsKvZcwggTjBgNVHREEggTaMIIE1oIIZGlyZWN0b3KCCiouZGlyZWN0b3KC
    F2RpcmVjdG9yLTAuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci0xLmRpcmVjdG9yLXBv
    ZIIXZGlyZWN0b3ItMi5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTMuZGlyZWN0b3It
    cG9kghdkaXJlY3Rvci00LmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItNS5kaXJlY3Rv
    ci1wb2SCF2RpcmVjdG9yLTYuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci03LmRpcmVj
    dG9yLXBvZIIXZGlyZWN0b3ItOC5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTkuZGly
    ZWN0b3ItcG9kghVkaXJlY3Rvci5kaXJlY3Rvci5zdmOCFyouZGlyZWN0b3IuZGly
    ZWN0b3Iuc3Zjgh9kaXJlY3Rvci0wLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJl
    Y3Rvci0xLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci0yLmRpcmVjdG9y
    LXBvZC51YWEuc3Zjgh9kaXJlY3Rvci0zLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9k
    aXJlY3Rvci00LmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci01LmRpcmVj
    dG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci02LmRpcmVjdG9yLXBvZC51YWEuc3Zj
    gh9kaXJlY3Rvci03LmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci04LmRp
    cmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci05LmRpcmVjdG9yLXBvZC51YWEu
    c3ZjgiNkaXJlY3Rvci5kaXJlY3Rvci5zdmMuY2x1c3Rlci5sb2NhbIIlKi5kaXJl
    Y3Rvci5kaXJlY3Rvci5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMC5kaXJl
    Y3Rvci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0xLmRpcmVj
    dG9yLXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTIuZGlyZWN0
    b3ItcG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMy5kaXJlY3Rv
    ci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci00LmRpcmVjdG9y
    LXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTUuZGlyZWN0b3It
    cG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItNi5kaXJlY3Rvci1w
    b2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci03LmRpcmVjdG9yLXBv
    ZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTguZGlyZWN0b3ItcG9k
    LnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItOS5kaXJlY3Rvci1wb2Qu
    dWFhLnN2Yy5jbHVzdGVyLmxvY2FsghJkaXJlY3Rvci5jZi1kZXYuaW+CFCouZGly
    ZWN0b3IuY2YtZGV2LmlvMA0GCSqGSIb3DQEBCwUAA4ICAQCOYmPAWvf00NbC5L3K
    FJ12e/3HZf3UVSidlKRtWKHWHyPuB9PgbqkrWzEsuzJmC+ZXNyJx+ZMGCtDmDSFn
    o2JQVkWQV5t9IcsTuP7xCzOYlljud769gnmAki8q+xAZusPIKQJ30T3KTOHCAo0c
    VsFVjRjurn2pi/DewW3TpPAMrMj5nlkBgEfK+8VQpJ2lFqXf4MgXOeIyE+stxYB0
    BiDfbddHoAcN5xCl0jQdM/wm8+wKRf2ghVo6JDbkZruAcfeXjID7le8R/7H6Lzo2
    1RWlqjKUYhLlXbKTlJ/x93SQEr/SCJYc94//f+Tzs69A7p4lF5kFIJJbvO0vtr0j
    k+9rk+pqKmfrCoDunXRPLbTLeFYOPm+iECU/uAuUpM4Wytfg17fwkCoFk3jx94qe
    QmIWl1OsLY6bot/8iJX9vUUbrp1AYmgG0I3Jmk4/uVxBjzjCXElCl4ZF1wjVQpZk
    G2X90GMsgxBKh+8gujLmVkpDCZ6a3etcRVaUngNoLkyAd+4voaBHoN+OemDzsdWh
    ISRhZloF/nrjJxat+ZjV2ybWRAbTTWy124lMvWK9YnhEu/TqzJbR6Suf0X4ySyPO
    j9cPnriCTQ1EHlTaD3AoI6WZ+wlZPJk1jDRPw6qsVpKjSI6FkgnFCyGmFScEU7Ps
    +TAtO9HMTrLg0lQyrjg0fTzLNA==
    -----END CERTIFICATE-----
  DIRECTOR_KEY: |
    -----BEGIN CERTIFICATE-----
    MIIJDzCCBvegAwIBAgIRAOZ3weoi+qSu319JGOEZAeEwDQYJKoZIhvcNAQELBQAw
    FTETMBEGA1UEAxMKaW50ZXJuYWxDQTAeFw0xNzA5MDEwMzA3NTFaFw0xOTA5MDEw
    MzA3NTFaMBMxETAPBgNVBAMTCGRpcmVjdG9yMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAvdpk6U7DxYv8PaFhH9KXFZ62Xrl3lAgAajyVQvcsG24x60Jt
    Ge/krPQIi1bO9K7Q2jl77txC7W1/b8gBSsRwiZk0qhxEY59+DE6nIyTebcm/Aci2
    ePjZB1QDkKKQAjNQVGXAjrBtKgMibOYedwdUGLPRfTx4OqC4Glx/7IUsuhuzjtzl
    ZwLjmkdMUr5K8GZCOkcIx3frGSO8t63H/lx38Ai0DU8LIZ3PsaTB4MfubnNVVAUw
    XeOsPERKzf7M3iGPZM6nb72ptNv4fQUB+rEaUukZRl2AhR/8U1z5rllB31LjiL5y
    ldy03B+1Yv0u6iGyPnpV0xrl1XnM1SCRNmPcIwIDAQABo4IFWjCCBVYwDgYDVR0P
    AQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4E
    FgQUf0bdCrkITJ0qiKd9OGESjTkk5mswHwYDVR0jBBgwFoAUZCn+ZXgUwsVy7ZSj
    Ftln+GsKvZcwggTjBgNVHREEggTaMIIE1oIIZGlyZWN0b3KCCiouZGlyZWN0b3KC
    F2RpcmVjdG9yLTAuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci0xLmRpcmVjdG9yLXBv
    ZIIXZGlyZWN0b3ItMi5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTMuZGlyZWN0b3It
    cG9kghdkaXJlY3Rvci00LmRpcmVjdG9yLXBvZIIXZGlyZWN0b3ItNS5kaXJlY3Rv
    ci1wb2SCF2RpcmVjdG9yLTYuZGlyZWN0b3ItcG9kghdkaXJlY3Rvci03LmRpcmVj
    dG9yLXBvZIIXZGlyZWN0b3ItOC5kaXJlY3Rvci1wb2SCF2RpcmVjdG9yLTkuZGly
    ZWN0b3ItcG9kghVkaXJlY3Rvci5kaXJlY3Rvci5zdmOCFyouZGlyZWN0b3IuZGly
    ZWN0b3Iuc3Zjgh9kaXJlY3Rvci0wLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJl
    Y3Rvci0xLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci0yLmRpcmVjdG9y
    LXBvZC51YWEuc3Zjgh9kaXJlY3Rvci0zLmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9k
    aXJlY3Rvci00LmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci01LmRpcmVj
    dG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci02LmRpcmVjdG9yLXBvZC51YWEuc3Zj
    gh9kaXJlY3Rvci03LmRpcmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci04LmRp
    cmVjdG9yLXBvZC51YWEuc3Zjgh9kaXJlY3Rvci05LmRpcmVjdG9yLXBvZC51YWEu
    c3ZjgiNkaXJlY3Rvci5kaXJlY3Rvci5zdmMuY2x1c3Rlci5sb2NhbIIlKi5kaXJl
    Y3Rvci5kaXJlY3Rvci5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMC5kaXJl
    Y3Rvci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci0xLmRpcmVj
    dG9yLXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTIuZGlyZWN0
    b3ItcG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItMy5kaXJlY3Rv
    ci1wb2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci00LmRpcmVjdG9y
    LXBvZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTUuZGlyZWN0b3It
    cG9kLnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItNi5kaXJlY3Rvci1w
    b2QudWFhLnN2Yy5jbHVzdGVyLmxvY2Fsgi1kaXJlY3Rvci03LmRpcmVjdG9yLXBv
    ZC51YWEuc3ZjLmNsdXN0ZXIubG9jYWyCLWRpcmVjdG9yLTguZGlyZWN0b3ItcG9k
    LnVhYS5zdmMuY2x1c3Rlci5sb2NhbIItZGlyZWN0b3ItOS5kaXJlY3Rvci1wb2Qu
    dWFhLnN2Yy5jbHVzdGVyLmxvY2FsghJkaXJlY3Rvci5jZi1kZXYuaW+CFCouZGly
    ZWN0b3IuY2YtZGV2LmlvMA0GCSqGSIb3DQEBCwUAA4ICAQCOYmPAWvf00NbC5L3K
    FJ12e/3HZf3UVSidlKRtWKHWHyPuB9PgbqkrWzEsuzJmC+ZXNyJx+ZMGCtDmDSFn
    o2JQVkWQV5t9IcsTuP7xCzOYlljud769gnmAki8q+xAZusPIKQJ30T3KTOHCAo0c
    VsFVjRjurn2pi/DewW3TpPAMrMj5nlkBgEfK+8VQpJ2lFqXf4MgXOeIyE+stxYB0
    BiDfbddHoAcN5xCl0jQdM/wm8+wKRf2ghVo6JDbkZruAcfeXjID7le8R/7H6Lzo2
    1RWlqjKUYhLlXbKTlJ/x93SQEr/SCJYc94//f+Tzs69A7p4lF5kFIJJbvO0vtr0j
    k+9rk+pqKmfrCoDunXRPLbTLeFYOPm+iECU/uAuUpM4Wytfg17fwkCoFk3jx94qe
    QmIWl1OsLY6bot/8iJX9vUUbrp1AYmgG0I3Jmk4/uVxBjzjCXElCl4ZF1wjVQpZk
    G2X90GMsgxBKh+8gujLmVkpDCZ6a3etcRVaUngNoLkyAd+4voaBHoN+OemDzsdWh
    ISRhZloF/nrjJxat+ZjV2ybWRAbTTWy124lMvWK9YnhEu/TqzJbR6Suf0X4ySyPO
    j9cPnriCTQ1EHlTaD3AoI6WZ+wlZPJk1jDRPw6qsVpKjSI6FkgnFCyGmFScEU7Ps
    +TAtO9HMTrLg0lQyrjg0fTzLNA==
    -----END CERTIFICATE-----
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAvdpk6U7DxYv8PaFhH9KXFZ62Xrl3lAgAajyVQvcsG24x60Jt
    Ge/krPQIi1bO9K7Q2jl77txC7W1/b8gBSsRwiZk0qhxEY59+DE6nIyTebcm/Aci2
    ePjZB1QDkKKQAjNQVGXAjrBtKgMibOYedwdUGLPRfTx4OqC4Glx/7IUsuhuzjtzl
    ZwLjmkdMUr5K8GZCOkcIx3frGSO8t63H/lx38Ai0DU8LIZ3PsaTB4MfubnNVVAUw
    XeOsPERKzf7M3iGPZM6nb72ptNv4fQUB+rEaUukZRl2AhR/8U1z5rllB31LjiL5y
    ldy03B+1Yv0u6iGyPnpV0xrl1XnM1SCRNmPcIwIDAQABAoIBAHfuVoDruNA6NgXY
    xDoOFlMaB6qfDuL8iwaRbtj2u244lmA/fhw8ZwC6yAr9s47uQBEa7yddDQpfeXlr
    pyVMIqtJlPNBGBK21jGAHiUdTUWdhIPj/yE8Uh1G/VmI1+AL+lrWTGXXHZ7EjCKu
    29/lSUKxlUy/vlOK48IDXOxU1IRblPFbr4ZmOygQSWFuwNlCNYC0aB5wRlqE9q+7
    VngIc4oyDDN4bf3+JRfvJJU5eGiCb9AsI1mYSO3tSzToTvsV7nEZpkxw1sdkWwfZ
    dKtnCz1Rtc/cpfe0MgBxKhR2ZF8JuSiCnuuQuELrlD4RnK+O4xrLxAhoyakVI1Zf
    98ZqkYECgYEA3BqPduqlLqMcIufGi7+nMncwIpSOzo444VbCUfu2fFLZEW7z+waV
    widZZ60BLe7CDy8o8xwIlvSsfzWpjRBJtJpL5d0JuxLGBdy2gXaal1Ymjaes66fK
    aXfAGHgvg1crPcP2qM+8RbtbStgP8C1DNethnE4qV4NjBm19oHPLpEsCgYEA3NDa
    tVyFqvu/dbATFr/wY7E4L723kFTT5WRFZ/C/VpIFZiJChHcqdsWUvF7TeuJdX44B
    kPjd/HUdc9L7JJNKnMNvqjxWBVZ6c/Xot5gM36od5P/6suoiHaNY8Zmw4yeN8oe2
    ekoDIAFUuKS2kLMzW3eP2jE1gJs2AwgXmU9E0IkCgYEAkIxg65fuI1K7h7Dvk5eq
    FlpwIkWuA7kjYdm4hF7q2XsPU4Oqd5E7iOaOsKfNvnyutYojOoWOnpTRNDnpv9qS
    jSlH7w3a9iC+K9tngF6D6B+L8jvMNHddVyZt4aQMkBUPMOEhfHvxCVqh+eUrknAn
    U6Hh2OT8qbx/rBj8CAQEGUECgYA6EuOyVwcAlP0hopEippA+Z9lzFN42I1knN1vZ
    nkN0LSsmVVRRKlYMrqITeIz+AJK2Es7upcUcJGD+mTpbwDEbUXsItp2ZAclqvf3a
    ay7XlBIQrBHvBAy85rz5rYYL99cpNfAT8Wso+7CgbxFktPyIzcUTiWWc0TU/Tt2G
    AIcEoQKBgCeOHrqx5GN95Xd/8g8A0doYfZNwkDJizqexTwh7HmFArYoyL1fUojIg
    KcdAUdsjMkaJnvs4GYcmN6m/nCUaT1i2RI8gOVrSstlL9ozPoe/B2F5Ws4zPTWTi
    t0O0qmxbvpT41ieIVMw4bVH/FKj9ffz/OO5oe/F43g5UYuVwzwCF
    -----END RSA PRIVATE KEY-----
  DNS_RECORD_NAME: null
  IP_ADDRESS: null
  KUBERNETES_NAMESPACE: null
kube:
  external_ip: 169.47.254.190
  storage_class:
    persistent: persistent
    shared: shared
